name: Deploy to GitHub Pages

env:
  NODE_VERSION: 18

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job 1: Checkout code
  ci_CHECKOUT:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # Job 2: Setup environment (Node.js)
  ci_SETUP:
    needs: ci_CHECKOUT
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

  # Job 3: Install dependencies and run tests
  ci_TEST:
    needs: ci_SETUP
    runs-on: ubuntu-22.04
    steps:
      - name: Install JavaScript dependencies
        run: npm i -f
        with:
          path: ./

      - name: Test application
        run: npm run test

  # Job 4: Build the site
  ci_BUILD:
    needs: ci_TEST
    runs-on: ubuntu-22.04
    steps:
      - name: Build the application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build # CRA build output folder

  # Job 5: Deploy to GitHub Pages
  cd_DEPLOY:
    needs: ci_BUILD
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4