name: Deploy to GitHub Pages

env:
  NODE_VERSION: 18

on:
  push:
    branches: ["master"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  CI_BUILD:
    runs-on: ubuntu-22.04
    steps:
    
      - name: CI/Checkout
        uses: actions/checkout@v4

      - name: CI/Setup Pages
        uses: actions/configure-pages@v5

      - name: CI/Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: CI/Install JavaScript dependencies
        run: npm i -f

      - name: Test Page
        run: npm run test

      - name: Build site
        run: npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./build # CRA build output folder

  # Deployment job
  CD_DEPLOY:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: CI_BUILD
    steps:
      - name: CD/Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5